feature/APSPlanner rename to ApsPlanner
Voyz/databay pull request #11
Opened 2020-10-04 05:36 UTC by Voyz

- renamed APSPlanner to ApsPlanner
- added APSPlanner wrapper class to warn of the deprecation

2020-10-04 18:30 UTC, cdpierse commented on databay/planners/aps_planner.py
> +        warnings.warn('APSPlanner was renamed to ApsPlanner and will be permanently changed in version 1.0', DeprecationWarning)
Might be worth also mentioning what version this change was brought in on in the warning. 
i.e.
`warnings.warn('APSPlanner was renamed to ApsPlanner in version 0.1.x and will be permanently changed in version 1.0', DeprecationWarning)`

2020-10-04 18:35 UTC, cdpierse requested changes
Everything looks really good besides possibly adding some extra detail about the version the change was implemented in the depreciation warning.

2020-10-06 23:04 UTC, Voyz commented
Good catch! Done 👍

2020-10-07 00:47 UTC, Voyz commented
Hold on, it just occurred to me: did you mean to include the actual version number, `0.1.7` instead of `0.1.x`? It would make more sense I guess, although may be tricky to nail that number down accurately before a release if releases get bumped or features get bumped. What do you recon?

2020-10-07 10:17 UTC, cdpierse commented
Yes I meant the actual version like `0.1.7` if we are in a situation where it's really clear to mark where the change occurred. Otherwise we might be better off sticking `0.1.7`.

2020-10-20 16:03 UTC, merged

2020-10-21 05:46 UTC, Voyz commented
Thanks for the review 👍